# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
   - name: dockerRegistryServiceConnection
     value: acrsampletesteu2
   - name: k8sNamespace
     value: employeeportal
   - name: imagepullsecret
     value: yIAZfIUQ2ISkMUTSE3xkP4xYJPRkY0sQou44JsunDV+ACRCxn75j

stages:

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubantu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
         
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(k8sNamespace)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yml
                $(System.ArtifactsDirectory)/manifests/service.yml
              # imagePullSecrets: |
              #   $(imagePullSecret)
              # containers: |
              #   $(containerRegistry)/$(imageRepository):$(tag)

