apiVersion: v1
kind: Pod
metadata:
  name: employee-producer-pod
  labels: 
    app: employee-producer-label
    type: employee-data-service
spec:
  containers:
    - name: employee-producer-pod
      image: kub-serviceconn.azurecr.io/employeeproducer:v1.0
      ports:
      - containerPort: 8000
