apiVersion: v1
kind: Pod
metadata:
  name: employee-producer-pod
  labels: 
    app: employee-producer-label
    type: employee-data-service
spec:
  containers:
    - name: employee-producer-pod
      image: aksbyexampleacr.azurecr.us/employee-producer:1.0-amd64
      ports:
      - containerPort: 8000

----
apiVersion: v1
kind: Pod
metadata:
  name: employee-cert-pod
  labels: 
    app: employee-cert-label
    type: employee-cert-service
spec:
  containers:
    - name: employee-cert-pod
      image: aksbyexampleacr.azurecr.us/employee-cert:1.0-amd64
      ports:
      - containerPort: 9000
